apiVersion: v1
data:
  s3.client.default.access_key: your_access_key
  s3.client.default.secret_key: your_secret_key
kind: Secret
metadata:
  creationTimestamp: "2025-10-30T05:27:44Z"
  name: elasticsearch-s3-credentials
  namespace: elk
  resourceVersion: "119244"
  uid: 846c3e66-38e1-4812-aed4-1763bd6c26e9
type: Opaque
